### ISSUE TITLE
[Crash Report] Using only Spline Tool

### ISSUE THREAD

**Issue by nserban** [GraphiteEditor/Graphite#1569]
**Describe the Crash**
Explain clearly what you were doing when the crash occurred.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite editor at https://editor.graphite.rs
2. Select a color
3. Start use Spline tool 
4. Start to draw a line using multiple points

**Additional Details**
Provide any further information or context that you think would be helpful in fixing the issue. Screenshots or video can be linked or attached to this issue.

**Browser and OS**
Chrome 120, Mac
Chrome Version 120.0.6099.216 (Official Build) (arm64) - OSX

**Stack Trace**
Copied from the crash dialog in the Graphite editor:

```
panicked at /var/lib/github-actions/_work/Graphite/Graphite/node-graph/gstd/src/any.rs:22:74:
DynAnyNode Input, Incorrect type, expected graphene_core::vector::vector_data::VectorData but found glam::f64::dvec2::DVec2 in:
graphene_std::any::FutureWrapperNode<graphene_core::vector::vector_nodes::SetFillNode<graphene_core::value::ClonedNode<graphene_core::vector::style::FillType>, graphene_core::value::ClonedNode<core::option::Option<graphene_core::raster::color::Color>>, graphene_core::value::ClonedNode<graphene_core::vector::style::GradientType>, graphene_core::value::ClonedNode<glam::f64::dvec2::DVec2>, graphene_core::value::ClonedNode<glam::f64::dvec2::DVec2>, graphene_core::value::ClonedNode<glam::f64::daffine2::DAffine2>, graphene_core::value::ClonedNode<alloc::vec::Vec<(f64, core::option::Option<graphene_core::raster::color::Color>)>>>>

Error
    at https://editor.graphite.rs/assets/index-c18f9d18.js:27:1143
    at h (https://editor.graphite.rs/assets/index-c18f9d18.js:15:34203)
    at Object.handleJsMessage (https://editor.graphite.rs/assets/index-c18f9d18.js:15:34351)
    at https://editor.graphite.rs/assets/index-c18f9d18.js:16:33012
    at https://editor.graphite.rs/assets/index-c18f9d18.js:16:29449
    at rt (https://editor.graphite.rs/assets/index-c18f9d18.js:16:1233)
    at o.wbg.__wbg_call_4c92f6aec1e1d6e6 (https://editor.graphite.rs/assets/index-c18f9d18.js:16:29415)
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1474]:0x3b62e0
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[4069]:0x4d6938
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[3692]:0x4bf2dd
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[6085]:0x55428d
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[3136]:0x497bd9
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x4269c6
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x426947
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x426947
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2298]:0x447634
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[620]:0x29b416
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2499]:0x45df33
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2307]:0x4484ea
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1099]:0x346e6b
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2405]:0x4551d1
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2305]:0x4481f0
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[519]:0x266a3b
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2490]:0x45d1e1
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x426947
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2298]:0x447634
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[620]:0x29b416
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2499]:0x45df33
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2307]:0x4484ea
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1099]:0x346e6b
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2405]:0x4551d1
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2305]:0x4481f0
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1103]:0x34a399
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1241]:0x3741a7
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x426a03
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1821]:0x402d7a
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1219]:0x3701f2
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[2037]:0x426a03
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[600]:0x292e6f
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[373]:0x1e619d
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[1738]:0x3f17fa
    at https://editor.graphite.rs/assets/graphite_wasm_bg-f097a9a7.wasm:wasm-function[6729]:0x55d740
    at Qc (https://editor.graphite.rs/assets/index-c18f9d18.js:16:433)
    at s (https://editor.graphite.rs/assets/index-c18f9d18.js:16:115)
```

**Comment by 0HyperCube** [comment]
Thanks for the report @nserban - could you please try and replicate it on https://11040e48.graphite.pages.dev/ and paste the console error here if it crashes? Many thanks.

**Comment by nserban** [comment]
I did not manage to reproduce it on https://11040e48.graphite.pages.dev/

**Comment by 0HyperCube** [comment]
OK thanks - that should now be fixed on https://dev.graphite.rs/ which will be deployed soon-ish. Thanks for reporting this.
