### ISSUE TITLE
[Crash Report] Crashes when deleting a two-side connected node.

### ISSUE THREAD

**Issue by pickaxe828** [GraphiteEditor/Graphite#896]
**Describe the Crash**
 Crashes when deleting two-side connected node.

**Steps To Reproduce**
Describe precisely how the crash occurred, step by step, starting with a new editor window.
1. Open the Graphite Editor at https://editor.graphite.rs
2. Use the `Node Graph Frame Tool` to make a rectangle
3. `Node Graph Frame` -> `Open Node Graph`
4. Right click to add any node (called as `Node A` from now on)
5. Connect both input and output to input and output of `Node A` respectively
6. Delete `Node A`
7. Crashes

**Additional Details**
Guessing this is due to output being empty.

**Browser and OS**
Chrome 108, Windows 10 or 11

**Stack Trace**
Copied from the crash dialog in the Graphite Editor:

```
panicked at 'called `Option::unwrap()` on a `None` value', node-graph\graph-craft\src\proto.rs:327:67

Error
    at eval (webpack-internal:///./src/io-managers/panic.ts:19:28)
    at Object.handleJsMessage (webpack-internal:///./src/wasm-communication/subscription-router.ts:42:17)
    at eval (webpack-internal:///./src/wasm-communication/editor.ts:77:23)
    at eval (webpack-internal:///./wasm/pkg/index_bg.js:1359:33)
    at handleError (webpack-internal:///./wasm/pkg/index_bg.js:365:18)
    at __wbg_call_3999bee59e9f7719 (webpack-internal:///./wasm/pkg/index_bg.js:1358:49)
    at js_sys::Function::call2::h5d32c2a40ee6730b (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[5063]:0x3e508b)
    at graphite_wasm::editor_api::JsEditorHandle::send_frontend_message_to_js::hb64dbd2feec94892 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[555]:0x2187bd)
    at std::thread::local::LocalKey<T>::with::h6fcf63598805a800 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[1419]:0x2e9ad4)
    at core::ops::function::Fn::call::h171f8b6d131a68a0 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[3761]:0x3baa67)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[3602]:0x3b28c7)
    at std::panicking::begin_panic_handler::{{closure}}::hb733f0aa505760cf (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[4081]:0x3c8b7e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6beefa0bcab220bc (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[5645]:0x3eec3b)
    at rust_begin_unwind (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[4971]:0x3e2fc6)
    at core::panicking::panic_fmt::h586d720a90aa8503 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[5449]:0x3ec2a9)
    at core::panicking::panic::h0859aaac783261b2 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[5285]:0x3e9701)
    at <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hc9db8e5ef4c4e5d5 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[2536]:0x36aa65)
    at graph_craft::proto::ProtoNetwork::replace_node_references::h26fe92511419aa57 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[1563]:0x2ff767)
    at graph_craft::proto::ProtoNetwork::reorder_ids::hb163aadc54ab4689 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[2038]:0x33a2e7)
    at <graphite_editor::messages::portfolio::portfolio_message_handler::PortfolioMessageHandler as graphite_editor::utility_traits::MessageHandler<graphite_editor::messages::portfolio::portfolio_message::PortfolioMessage,(&graphite_editor::messages::input_preprocessor::input_preprocessor_message_handler::InputPreprocessorMessageHandler,&graphite_editor::messages::preferences::preferences_message_handler::PreferencesMessageHandler)>>::process_message::h3f19ddc1723f26c4 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[56]:0x34e61)
    at graphite_editor::dispatcher::Dispatcher::handle_message::hbe60067c90946cbc (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[143]:0x101e7b)
    at std::thread::local::LocalKey<T>::with::hc9128b19b0e0377b (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[1632]:0x309270)
    at graphite_wasm::editor_api::JsEditorHandle::dispatch::he3433a4c24c0bbc8 (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[2689]:0x377468)
    at jseditorhandle_processNodeGraphFrame (http://localhost:8080/590dad9e86b49c3f.module.wasm:wasm-function[3808]:0x3bce8d)
    at Proxy.processNodeGraphFrame (webpack-internal:///./wasm/pkg/index_bg.js:1031:53)
    at Proxy.eval (webpack-internal:///./src/utility-functions/panic-proxy.ts:34:42)
    at eval (webpack-internal:///./src/state-providers/portfolio.ts:95:29)
```

**Comment by pickaxe828** [comment]
Fix in previous commits.
